<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [1]:
import numpy as np
a = np.array ([1,2,3])
print (a)

[1 2 3]


In [5]:
b = np.array ([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#create a constant array with all values are 6 
d = np.full ((4,4),6) #This is an example of square matrix
print (d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [13]:
e = np.diagonal ([[1,2,3],[4,5,6],[7,8,9]])
print (e)

[1 5 9]


In [ ]:
#Identity Matrix
f = np.eye

In [15]:
#Zero matrix
g = np.zeros((6,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#Empty Matrix
h = np.empty ((0,5))
print (h)

[]


In [19]:
#Addition Matrix
i = np.array ([[1,2,3],[4,5,6],[7,8,9]])
j = np.zeros ((3,3))
print (i+j)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
#Subtraction Matrix
i = np.array ([[1,2,3],[4,5,6]])
j = np.array ([[3,4,5],[6,7,8]])
print (i-j)

[[-2 -2 -2]
 [-2 -2 -2]]
