<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

In [14]:
import numpy as np

#Question 1  Create a Python code that displays a square matrix whose length is 5 (10 points)
#arranging number range from 1-26, reshape to 5x5 matrix
np.arange(1, 26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
#Question 2 Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)
#numpy 3x3 upper triangle matrix where zero is below the principal diagonal
#the diagonal int parameter is set to default (0)
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [61]:
#Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)
#creating matrix
S = np.array([[0,2,4],[-2,0,3],[-4,-3,0]])
print (S, "\n")

#transpose function checking for symmetric matrix
print(np.transpose(S))

[[ 0  2  4]
 [-2  0  3]
 [-4 -3  0]] 

[[ 0 -2 -4]
 [ 2  0 -3]
 [ 4  3  0]]


In [55]:
#Question 4 What is the inverse of matrix C? Show your solution by python coding. (20 points)
#Creating the given matrix
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])

#Inversing the matrix C
c = np.linalg.inv(C)
print ('Matrix C\n',C)
print ('Inverse\n',c)

Matrix C
 [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
Inverse
 [[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [54]:
#Question 5 What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)
#linalg.det - numpy function for computing determinant
#result without rounding off
print ((np.linalg.det(C)))

#round off result
print (round(np.linalg.det(C)))

5.000000000000001
5


In [53]:
# Question 6 Find the roots of the linear equations by showing its python codes (30 points)
#creating given matrix
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print (A)
inv_A = np.linalg.inv(A)

B = np.array([[3.4],[8.8],[19.2]])
print (B)

#AA^-1X = B.A^-1
X = np.dot(inv_A,B)
print ("\n roots of the linear equation \n", X)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 3.4]
 [ 8.8]
 [19.2]]

 roots of the linear equation 
 [[0.2]
 [0.4]
 [0.8]]
