<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

In [ ]:
import numpy as np

#Given Matrices
W = np.array ([[1,-3],[2,-2],[3,1]])
X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array ([[1,2,0],[0,-1,2]])
Z = np.array ([[0,1],[2,3]])

#PROBLEM 1 

In [ ]:
#a. WY
WY = np.dot(W,Y)
print (WY)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [ ]:
#b. Z + Z
print (Z + Z)

[[0 2]
 [4 6]]


In [ ]:
#c. 3X
C= np.multiply(3,X)
print(C)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


#PROBLEM 2

In [49]:
#a. The product (YW)^2 is not defined
YW = np.dot(Y,W)
print (np.square(YW))

if YW is None:
    print("The statement is TRUE")
else:
    print("The statement is FALSE")

#The matrix is defined, therefore the statement is FALSE

[[25 49]
 [16 16]]
The statement is FALSE


In [57]:
#b. WY - X = 
A = np.dot(W,Y)
b = A - X
print (b)

x = np.array ([[-2,3,-7],[3,4,-7],[1,6,1]])

if (np.array_equiv(x,b)):
  print("The statement is TRUE")
else:
  print("The statement is FALSE")

#The statement is TRUE

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
The statement is TRUE


In [59]:
#c. YW – Z^2 =
YW = np.dot(Y,W)
c = YW - np.square(Z)
print (c)

z = np.array ([[5,-9],[0,2]])

if (np.array_equiv(z,c)):
  print("The statement is TRUE")
else:
  print("The statement is FALSE")
#The statement is FALSE

[[ 5 -8]
 [ 0 -5]]
The statement is FALSE
