<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Transformation

In [7]:
import numpy as np

#creating the given matrix
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
print (A, "\n")
inv_A = np.linalg.inv(A)
B = np.array([[5],[6],[8]])


#AA^-1X = B.A^-1
X = np.dot(inv_A,B)
print (X)

[[1 1 1]
 [1 2 2]
 [1 2 3]] 

[[ 4.]
 [-1.]
 [ 2.]]
