<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program for Inverse and Transpose of Matrices

In [3]:
import numpy as np

#Converting decimal values into fraction
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

#3x3 Matrix and its Inverse and Transpose

In [43]:
#Creating 3x3 array
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A, "\n")

#Condition for inverse if the given matrix has 0 determinent or not
if (np.linalg.det(A)):
    #Inverse matrix using linalg.inv function
    A_inverse = (np.linalg.inv(A))
    print("INVERSE \n", A_inverse, "\n")
else:
    print("Cannot be inverse, Singular Matrix")

#Transpose matrix using transpose method
A_transpose = A.transpose()
print ("TRANSPOSE \n", A_transpose)


[[6 1 1]
 [4 -2 5]
 [2 8 7]] 

INVERSE 
 [[3/17 -1/306 -7/306]
 [1/17 -20/153 13/153]
 [-2/17 23/153 8/153]] 

TRANSPOSE 
 [[6 4 2]
 [1 -2 8]
 [1 5 7]]


#4x4 Matrix and its Inverse and Transpose

In [40]:
#Creating 4x4 array
##The given matrix is Singular Matrix which has a determinant of 0 therefore it cannot be inversed
B = np.arange(1,17).reshape(4, 4)
print (B)

#Condition for inverse if the given matrix has 0 determinent or not
if (np.linalg.det(B)):
   #Inverse matrix using linalg.inv function
    B_inverse = (np.linalg.inv(B))
    print("INVERSE \n", B_inverse)
else:
    print("Cannot be inverse, Singular Matrix")


#Transpose matrix using transpose method
B_transpose = B.transpose()
print ("\nTRANSPOSE \n", B_transpose)


[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]]
Cannot be inverse, Singular Matrix

TRANSPOSE 
 [[1 5 9 13]
 [2 6 10 14]
 [3 7 11 15]
 [4 8 12 16]]
