<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [13]:
import numpy as np

A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])

#ADDITION OPERATION
print (A+B, " = A + B", "\n")

#SUBTRACTION 1
print (A-B, " = A - B", "\n")

#SUBTRACTION 2
print (B-B, " = B - B", "\n")



[[ 1 -3]
 [ 6  4]]  = A + B 

[[-11   3]
 [  2  -2]]  = A - B 

[[0 0]
 [0 0]]  = B - B 

