<a href="https://colab.research.google.com/github/ryanmaullon/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Spaces and its Operations

In [2]:
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])

print('Vector A is', A)
print('Vector A is', B)

Vector A is [4 3]
Vector A is [ 2 -5]


In [7]:
#Checking shapes
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.size

6

#Vector Addition

In [10]:
R = np.add(A,B)
R

array([ 6, -2])

In [8]:
R = (A + B)
print(R)

[ 6 -2]


#Vector Subtraction

In [11]:
R = np.subtract(A,B)
R

array([2, 8])

#Vector Scaling

In [13]:
A = np.array([1,5,8,9])
S = 5 * A
print(S)

[ 5 25 40 45]


In [15]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


In [18]:
A = np.array([2,3,4])
B = np.array([1,7,0])

#compute cross product
output = np.cross(A,B)

print(output)

[-28   4  11]
